name: build-and-test
run-name: "Build and Test"
on: [push]

env:
  # Used to parameterize these build scripts between LancachePrefill projects
  PROJECT_NAME: LancacheFileDeleter

jobs:
  build-test:
    uses: tpill90/lancache-prefill-common/.github/workflows/build-and-test-template.yml@main
    with:
      PROJECT_NAME: LancacheFileDeleter